ball:
  gravity: 9.81
  radius: 0.02
  mass: 0.0027
  coefficient_of_drag: 0.47
  coefficient_of_lift: 1.23
  air_density: 1.205
table:
  height: 0.76
  width: 1.525
  length: 2.74
  net_height: 0.1525  
  net_width: 1.835  